# Generated by Django 5.2.1 on 2025-06-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='results/'),
        ),
    ]
