# Generated by Django 5.2.1 on 2025-06-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_testresult_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
